# ui.R

# the following packages are required before commerce the program
# install.packages(c("shinydashboard", "DT","shiny", "ggplot2", "gplots", "tidyverse", "heatmaply",
#               "RColorBrewer", "plotly", "networkD3", "igraph", "reshape2"))
#   source("http://bioconductor.org/biocLite.R")
#   biocLite("limma")

## Load required packages
library(shiny)
library(shinydashboard)
library(DT)
library(ggplot2)
library(gplots)
library(limma)
library(heatmaply)
library(RColorBrewer)
library(tidyverse)
library(plotly)
library(networkD3)
library(igraph)
library(reshape2)


# start ui
header <- dashboardHeader(
  title = "CML GEP App"
)


sidebar <- dashboardSidebar( 
  sidebarMenu(id="menu1",
              menuItem("Introduction", icon = icon("user"),
                       menuSubItem("Introduction", tabName = "intro")
              ),
              menuItem("Global analysis", icon = icon("bar-chart-o"),
                       menuSubItem("MDS & dendrogram", tabName = "mds_dendro"),
                       menuSubItem("Heatmap", tabName = "HeatmapSamples")
              ),
              menuItem("group analysis", icon = icon("bar-chart-o"),
                       menuSubItem("Comparison Analysis", tabName="cpanalysis"),
                       menuSubItem("Gene specific search", tabName = "GeneSearch"),
                       menuSubItem("network Analysis", tabName = "network")
              ),

              menuItem("Feedback", icon = icon("comment", lib="glyphicon"), tabName="feedback")
              
  )
  ,helpText("Developed by Chung Kok @ 2018")
)


body <- dashboardBody(
  tabItems(
    ## Introduction tab panel
    tabItem(tabName="intro",
            h2("Introduction"),
            p("Chronic-phase Chronic myeloid leukaemia (CP-CML) is a blood cancer that affects 
              the blood and bone marrow. In CML, it produces high white blood cells counts that 
              interfere with normal blood cell production. In Australia, there are 330 people 
              diagnosed with CML each year."),
            p("Finding the effective drug treatment has been challenging for the past decades. 
              With the improvement in the technologies, more detailed data can be harvested."),
            p("In this project, gene expression data generated by the next-generation sequencing, 
              and in combination with interactive visualisation tools for effective communication, 
              will allow us to identify potential drug targets for the cancer."), 
            p("The interactive visualisation created in this project provides targeted audience 
              such as biologists and clinicians an easy and fun way to navigate and understand 
              the data effectively."),
            p("The raw data was downloaded from the publicly available database with the SRA accession
              number SRP028528")
    ),
    ## MDS and dendrogram tab panel
    tabItem(tabName="mds_dendro",
            fluidRow(
              box(title = "control panel",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 4,
                  
                  fluidRow(
                    box(title = "Top genes selection",
                        solidHeader = T, status = "warning",
                        width = 12,
                        fluidRow(
                          column(12,
                                 sliderInput("topGenes", "Top most variable genes:",
                                             min = 50, max = 1000, step = 50, value = 50)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("ncluster", "Number of clusters:",
                                             min = 1, max = 17, step = 1, value = 1)
                                 )
                        )
                    )
                  )
              ),
              box(title="Multi-dimensional plot based on top most variable genes",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 8,
                  
                  column(12,
                         plotlyOutput("mdsplot")
                  )
                  
              )
            ),
            fluidRow(
              box(title = "dendrogram analysis based on top most variable genes",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 12,

              column(12,
                     dendroNetworkOutput("dendro"))
              )
            )
    ),
    ## heatmap tab panel
    tabItem(tabName = "HeatmapSamples",
            fluidRow(
              box(title = "control panel",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 4,
                  
                  fluidRow(
                    box(title = "Top genes selection",
                        solidHeader = T, status = "warning",
                        width = 12,
                        fluidRow(
                          column(12,
                                 sliderInput("topGeneH", "Top most variable genes:",
                                             min = 10, max = 1000, step = 10, value = 10)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("heatmapFontsize", "Heatmap Gene font size:",
                                             min = 0.1, max = 10, step = 0.1, value = 7)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("heatmapSampleFontsize", "Heatmap Sample font size:",
                                             min = 0.1, max = 10, step = 0.1, value = 7)
                          )
                        )
                    )
                  )
              ),
              box(title="Sample Information Table",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 8,
                  
                  column(12,
                         dataTableOutput("sampleTable")
                  )
              )
            ),
            fluidRow(
              box(title = "Heatmap plot based on top most variable genes",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 12,
                  
                  column(12,
                         #d3heatmapOutput("heatmap")
                         plotlyOutput("heatmap")
                  )
              )
            )
    ),
    ## comparison analysis tab panel
    tabItem(tabName="cpanalysis",
             fluidRow(
               box(title = "control panel",
                   solidHeader = T, status = "info",
                   collapsible = T, collapsed = F,
                   width = 3,
                   
                   fluidRow(
                     box(title = "Dataset",
                         solidHeader = T, status = "warning",
                         width = 12,
                         fluidRow(
                           column(12,
                                  selectInput("dataset", "choose a dataset:",
                                              list(`BC1 vs BC2` = "data",
                                                   `BC1 vs CP` = "data1",
                                                   `BC2 vs CP` = "data2",
                                                   `BC vs CP` = "data3")
                                  )
                           )
                         ),
                         fluidRow(
                           column(12,
                                  textInput(inputId="fdr",
                                            label="FDR adjusted p-value (range 0-1 value)",
                                            value = 0.05)
                           )
                         ),
                         fluidRow(
                           column(12,
                                  textInput(inputId="fc",
                                            label="log2 Fold Change (positive value)",
                                            value = 1)
                           )
                         )
                     )
                   )
               ),
                     
               box(title = "stripchart analysis",
                   solidHeader = T, status = "info",
                   collapsible = T, collapsed = F,
                   width = 9,
                   
                   fluidRow(
                     column(12,
                            plotlyOutput("genechart")
                     )
                   )
               )
             ),
            fluidRow(
              box(title = "Scatter plot",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 12,
                  
                  fluidRow(
                    box(title = "Volcano plot",
                        solidHeader = T, status = "info",
                        width = 12,
                        fluidRow(
                          column(12,
                                 plotlyOutput("volcanoPlot")
                                 )
                        )
                    )
                  ),
                  fluidRow(
                    box(title = "Selected Gene Info",
                        solidHeader = T, status = "info",
                        width = 12,
                        fluidRow(
                          column(12,
                                 dataTableOutput("selectedGeneTable")
                          )
                        )
                    )
                  )
              )
            )
    ),
    ## gene specific search tab panel
    tabItem(tabName = "GeneSearch",
            fluidRow(
              box(title = "control panel",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 3,
                  
                  fluidRow(
                    box(title = "Dataset",
                        solidHeader = T, status = "warning",
                        width = 12,
                        fluidRow(
                          column(12,
                                 selectInput("dataset_gs", "choose a dataset:",
                                             list(`BC1 vs BC2` = "data",
                                                  `BC1 vs CP` = "data1",
                                                  `BC2 vs CP` = "data2",
                                                  `BC vs CP` = "data3")
                                 )
                          )
                        ),
                        fluidRow(
                          column(12,
                                 textInput(inputId="fdr_gs",
                                           label="FDR adjusted p-value (range 0-1 value)",
                                           value = 0.05)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 textInput(inputId="fc_gs",
                                           label="log2 Fold Change (positive value)",
                                           value = 1)
                          )
                        )
                    )
                  )
              ),
              box(title = "stripchart analysis",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 9,
                  
                  fluidRow(
                    column(12,
                           plotlyOutput("genechart_gs")
                    )
                  )
              ),
              box(title = "Gene expression Table",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 12,
                  
                  fluidRow(
                    column(12,
                           DT::dataTableOutput("sigTable")
                    )
                  )
              )
            )
    ),
    ## network analysis tab panel
    tabItem(tabName = "network",
            fluidRow(
              box(title = "control panel",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 3,
                  
                  
                  fluidRow(
                    box(title = "Dataset",
                        solidHeader = T, status = "warning",
                        width = 12,
                        fluidRow(
                          column(12,
                                 selectInput("dataset_network", "choose a dataset:",
                                             list(`BC1 vs BC2` = "data",
                                                  `BC1 vs CP` = "data1",
                                                  `BC2 vs CP` = "data2",
                                                  `BC vs CP` = "data3")
                                 )
                          )
                        ),
                        fluidRow(
                          column(12,
                                 textInput(inputId="fdr_network",
                                           label="FDR adjusted p-value (range 0-1 value)",
                                           value = 0.05)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 textInput(inputId="fc_network",
                                           label="log2 Fold Change (positive value)",
                                           value = 1)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("topnetworkgenes", "Number of input genes:",
                                             min = 10, max = 200, step = 10, value = 50)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("opacity", "Opacity", 
                                             min = 0.1, max = 1, step = .1, value = 1)
                          )
                        ),
                        fluidRow(
                          column(12,
                                 sliderInput("minCluster", "Min Cluster size", 
                                             min = 1, max = 20, step = 1, value = 10)
                          )
                        )
                    )
                  )
              ),
              box(title = "Network analysis",
                  solidHeader = T, status = "info",
                  collapsible = T, collapsed = F,
                  width = 9,
                  
                  fluidRow(
                    column(12,
                           forceNetworkOutput("force")
                    )
                  )
              )
            )
    ),
    ## feedback tab panel
    tabItem(tabName='feedback',
            h2("Feedback"),
            p("This app is developed and maintained by Chung Kok."),
            p("If you have any questions, comments, or suggestions, 
              feel free to contact me at ckok0001@student.monash.edu"),
            br()
    )
  )
)

ui <- dashboardPage(header, sidebar, body, skin = "green")
